version: '3.8'

services:
  pgsql:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - database:/var/lib/postgresql/data
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 1s
      timeout: 1s
      retries: 15
  tests:
    image: node:19
    working_dir: /kiss-orm
    depends_on:
      pgsql:
          condition: service_started
      mysql:
          condition: service_healthy
    command: npx ts-node ./node_modules/jasmine/bin/jasmine --config=jasmine.json
    volumes:
      - $PWD:/kiss-orm
volumes:
  database:
